services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devkit_api
    volumes:
      - ./config:/app/config
    image: devkit_api
    ports:
      - 9091:9091
    command: [ "/app/main" ]

